siteUid: null
sortOrder: 7
template: /freeform-demo/bootstrap/view
uriParts:
  - freeform-demo/bootstrap/
  -
    - slug
    - '[^\/]+'
  - /success
uriPattern: 'freeform-demo/bootstrap/<slug:[^\/]+>/success'
