siteUid: null
sortOrder: 1
template: /freeform-demo/bootstrap/view_submission
uriParts:
  - freeform-demo/bootstrap/
  -
    - slug
    - '[^\/]+'
  - /submissions/
  -
    - id
    - \d+
  - /success
uriPattern: 'freeform-demo/bootstrap/<slug:[^\/]+>/submissions/<id:\d+>/success'
