field: 02840bd5-3249-46e9-8eff-2650829c92bb
fieldLayouts:
  bebe6d93-f20a-44f6-ac22-0dc098fa46bb:
    tabs:
      -
        elements:
          -
            fieldUid: 6feef228-405c-4751-9375-a922f25caaeb
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 617c9d1b-e97d-4206-90f2-cf67835da704
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 77ba0029-6800-407d-974c-7336f6bdddaa
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b7be0c27-81f4-4c2c-8eea-429212b45d89
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b79a4e73-9fb8-402f-8fa9-cc175ffec5a1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cf7d320c-d6d0-4a44-81f3-d150aa017222
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3cce9d87-0235-45c2-a5d1-959ba9d862bd
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  3cce9d87-0235-45c2-a5d1-959ba9d862bd:
    contentColumnType: text
    fieldGroup: null
    handle: buttonLink
    instructions: 'If you supply a button link, it will override the internal link, so make sure you only select one option here.'
    name: 'External link'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  617c9d1b-e97d-4206-90f2-cf67835da704:
    contentColumnType: string
    fieldGroup: null
    handle: mobileImage
    instructions: 'Upload an image here to show on mobile view. If you don''t upload one, the main image will be used on desktop and mobile versions.'
    name: 'Mobile image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:72ae913b-01d4-4be5-bab1-e0ffc26c8a70'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Add an image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:72ae913b-01d4-4be5-bab1-e0ffc26c8a70'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:72ae913b-01d4-4be5-bab1-e0ffc26c8a70'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  6feef228-405c-4751-9375-a922f25caaeb:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: 'This is the image that will be used in the slideshow for larger screen sizes.'
    name: 'Desktop Image'
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:72ae913b-01d4-4be5-bab1-e0ffc26c8a70'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: 'Add an image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:72ae913b-01d4-4be5-bab1-e0ffc26c8a70'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  77ba0029-6800-407d-974c-7336f6bdddaa:
    contentColumnType: text
    fieldGroup: null
    handle: slideshowText
    instructions: ''
    name: 'Slideshow Text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b79a4e73-9fb8-402f-8fa9-cc175ffec5a1:
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: ''
    name: 'Button Text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b7be0c27-81f4-4c2c-8eea-429212b45d89:
    contentColumnType: text
    fieldGroup: null
    handle: slideshowSubheading
    instructions: ''
    name: 'Slideshow subheading'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cf7d320c-d6d0-4a44-81f3-d150aa017222:
    contentColumnType: string
    fieldGroup: null
    handle: internalLink
    instructions: 'If the slideshow is linking to a page or entry on our site then use this field.'
    name: 'Internal link'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: slideshow
name: Slideshow
sortOrder: 1
