field: 900919f1-9e83-4ba0-8c29-1877804aeee2
fieldLayouts:
  293d4a6e-27e4-49fc-811b-99b882974414:
    tabs:
      -
        fields:
          48c25a60-0cc4-4764-82d0-e6eede8eab59:
            required: false
            sortOrder: 3
          51cbca5e-f2ae-41b0-a832-c1157a8f70af:
            required: false
            sortOrder: 2
          5df7e1a1-f735-447f-913b-2b5bd900d524:
            required: false
            sortOrder: 4
          8cb86565-0146-4d5e-813e-47a72931b11d:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  48c25a60-0cc4-4764-82d0-e6eede8eab59:
    contentColumnType: text
    fieldGroup: null
    handle: columnTwoContent
    instructions: ''
    name: Content
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Standard.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  51cbca5e-f2ae-41b0-a832-c1157a8f70af:
    contentColumnType: string
    fieldGroup: null
    handle: columnOneBackgroundImage
    instructions: ''
    name: 'Background Image'
    searchable: false
    settings:
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:72ae913b-01d4-4be5-bab1-e0ffc26c8a70'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: 'Add a background image'
      singleUploadLocationSource: 'volume:72ae913b-01d4-4be5-bab1-e0ffc26c8a70'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: '1'
      validateRelatedElements: ''
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  5df7e1a1-f735-447f-913b-2b5bd900d524:
    contentColumnType: string
    fieldGroup: null
    handle: columnTwoBackgroundImage
    instructions: ''
    name: 'Background Image'
    searchable: false
    settings:
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:72ae913b-01d4-4be5-bab1-e0ffc26c8a70'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: 'Add a background image'
      singleUploadLocationSource: 'volume:72ae913b-01d4-4be5-bab1-e0ffc26c8a70'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: '1'
      validateRelatedElements: ''
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  8cb86565-0146-4d5e-813e-47a72931b11d:
    contentColumnType: text
    fieldGroup: null
    handle: columnOneContent
    instructions: ''
    name: Content
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Standard.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: twoColumns
name: 'Two Columns'
sortOrder: 4
