fieldLayouts:
  cbbad6d1-ee93-4250-b860-78bd77a352c4:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: d626b7c4-490f-4aaf-ace0-91ffd757b01a
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: f34ad8a7-0c0a-4008-acbe-6f792087222f
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 62611260-acf6-4eaa-a116-7df881e27bd8
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 4a2ebf56-7832-4077-8a6d-4325cef17dbb
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 22bf9de7-7598-4ae0-b9b6-7e8c9466a747
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 413d8769-4db4-4d8a-a47b-ae88f100206d
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Actions Taken'
        sortOrder: 1
handle: actionsTaken
hasTitleField: true
name: 'Actions Taken'
section: 923d663f-22e9-4786-8469-3534bc15f38f
sortOrder: 1
titleFormat: ''
