fieldLayouts:
  09bdd1eb-8b23-4e82-ae0e-8a5f135a939e:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: b1567a16-e716-4948-9b1b-e644e0c925c3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3f90a1f4-e99b-4282-9a35-693f82af1118
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Contact us'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 7bf738e1-3bb2-45f6-ac54-c9385d07d952
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8275cae2-520b-4aa3-ad6e-e436d430c6bf
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4f2ceb84-b609-4765-8a3c-1bb92e61e08f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 15396392-b2d0-4259-b386-ff3bf7a2da20
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ac7a53bb-d5a3-45b5-b06d-13719eaae4eb
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'SEO Fields'
        sortOrder: 2
handle: contactUs
hasTitleField: true
name: 'Contact us'
section: 739c043d-cdbd-4681-8d30-f919a424604a
sortOrder: 8
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: ''
