fieldLayouts:
  8025f53a-0ffc-4e90-90cf-9ed6c7be2e25:
    tabs:
      -
        elements:
          -
            instructions: null
            label: 'Page title'
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 02840bd5-3249-46e9-8eff-2650829c92bb
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: fb4bae98-1902-4611-9b1c-635f478d5575
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: ac7a53bb-d5a3-45b5-b06d-13719eaae4eb
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 7bf738e1-3bb2-45f6-ac54-c9385d07d952
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 15396392-b2d0-4259-b386-ff3bf7a2da20
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 8275cae2-520b-4aa3-ad6e-e436d430c6bf
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 4f2ceb84-b609-4765-8a3c-1bb92e61e08f
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'SEO Fields'
        sortOrder: 2
handle: homepage
hasTitleField: true
name: Homepage
section: 38ecca30-5b80-4425-957a-fce4b59f551b
sortOrder: 1
titleFormat: '{section.name|raw}'
