childBlocks: ''
field: fb4bae98-1902-4611-9b1c-635f478d5575
fieldLayouts:
  40314cb3-3668-4d41-8700-a10b521b6545:
    tabs:
      -
        elements:
          -
            fieldUid: aea0f145-e645-4cc0-a527-40ec2aa6a934
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: e7b2fe6b-98c7-4eb1-a270-83d982092073
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f89d0c99-6a52-4949-b745-a11c9955c3b8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 2
handle: columns
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Columns
sortOrder: 22
topLevel: false
