childBlocks: ''
field: fb4bae98-1902-4611-9b1c-635f478d5575
fieldLayouts:
  40314cb3-3668-4d41-8700-a10b521b6545:
    tabs:
      -
        fields:
          aea0f145-e645-4cc0-a527-40ec2aa6a934:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
      -
        fields:
          e7b2fe6b-98c7-4eb1-a270-83d982092073:
            required: false
            sortOrder: 1
          f89d0c99-6a52-4949-b745-a11c9955c3b8:
            required: false
            sortOrder: 2
        name: Settings
        sortOrder: 2
handle: columns
maxBlocks: 0
maxChildBlocks: 0
name: Columns
sortOrder: 20
topLevel: false
