childBlocks: ''
field: fb4bae98-1902-4611-9b1c-635f478d5575
fieldLayouts:
  0f1b9ed8-1188-49b8-a373-8f7b69cbc560:
    tabs:
      -
        elements:
          -
            fieldUid: b1567a16-e716-4948-9b1b-e644e0c925c3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: contactUs
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Contact us'
sortOrder: 17
topLevel: false
