childBlocks: ''
field: fb4bae98-1902-4611-9b1c-635f478d5575
fieldLayouts:
  8f47e1e4-33a3-40bd-9bcd-e8b775877aa2:
    tabs:
      -
        fields:
          41e08df9-c20f-426a-98df-d1a4ada3724d:
            required: false
            sortOrder: 2
          5a39aec0-dd22-403a-adaa-95157ed5d665:
            required: false
            sortOrder: 1
        name: 'Media releases'
        sortOrder: 1
handle: mediaReleases
maxBlocks: 0
maxChildBlocks: 0
name: 'Media releases'
sortOrder: 22
topLevel: false
