childBlocks: ''
field: fb4bae98-1902-4611-9b1c-635f478d5575
fieldLayouts:
  9c7ea731-f546-4b5e-9ab1-adfcaf16ffca:
    tabs:
      -
        elements:
          -
            fieldUid: 7b955f65-3cc5-42fe-b596-b2d7c320b45a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fb1dd9e5-7848-43a8-8c35-dffa917e1efa
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: CONTENT
        sortOrder: 1
handle: reports
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Reports
sortOrder: 25
topLevel: false
