childBlocks: ''
field: fb4bae98-1902-4611-9b1c-635f478d5575
fieldLayouts:
  -
    tabs:
      -
        elements:
          -
            fieldUid: 5a39aec0-dd22-403a-adaa-95157ed5d665
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 55d9c451-98eb-4346-b08c-f5c595ba79e5
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: richText
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Rich Text'
sortOrder: 3
topLevel: false
