childBlocks: ''
field: fb4bae98-1902-4611-9b1c-635f478d5575
fieldLayouts:
  19487ef7-9100-4b55-af98-e9ad1dede0cf:
    tabs:
      -
        fields:
          55d9c451-98eb-4346-b08c-f5c595ba79e5:
            required: false
            sortOrder: 2
          5a39aec0-dd22-403a-adaa-95157ed5d665:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
handle: richText
maxBlocks: 0
maxChildBlocks: 0
name: 'Rich Text'
sortOrder: 3
topLevel: false
