childBlocks: ''
field: fb4bae98-1902-4611-9b1c-635f478d5575
fieldLayouts:
  -
    tabs:
      -
        elements:
          -
            fieldUid: 0c2487f9-4bfe-497f-9192-00e8553bc831
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: e7b2fe6b-98c7-4eb1-a270-83d982092073
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 2
handle: siteSelector
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Site selector'
sortOrder: 11
topLevel: false
