childBlocks: ''
field: fb4bae98-1902-4611-9b1c-635f478d5575
fieldLayouts:
  8c3853ee-da6a-407a-a060-b7a474f52314:
    tabs:
      -
        fields:
          0c2487f9-4bfe-497f-9192-00e8553bc831:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
      -
        fields:
          e7b2fe6b-98c7-4eb1-a270-83d982092073:
            required: false
            sortOrder: 1
        name: Settings
        sortOrder: 2
handle: siteSelector
maxBlocks: 0
maxChildBlocks: 0
name: 'Site selector'
sortOrder: 11
topLevel: false
