childBlocks: ''
field: fb4bae98-1902-4611-9b1c-635f478d5575
fieldLayouts:
  c926adec-3ce6-42ea-bacd-89f81113c9f0:
    tabs:
      -
        elements:
          -
            fieldUid: 74078c38-389e-449d-b073-5a0a90341e2f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: spacer
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Spacer
sortOrder: 16
topLevel: false
