childBlocks: ''
field: fb4bae98-1902-4611-9b1c-635f478d5575
fieldLayouts:
  -
    tabs:
      -
        elements:
          -
            fieldUid: 239cfa8e-2ebf-4caf-8ecb-254355970e79
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Table matrix'
        sortOrder: 1
handle: table
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Table
sortOrder: 14
topLevel: false
