childBlocks: ''
field: fb4bae98-1902-4611-9b1c-635f478d5575
fieldLayouts:
  -
    tabs:
      -
        elements:
          -
            fieldUid: f7a2f435-dbae-4b79-83b1-2c22e1d34d04
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c90191a0-6157-4f70-aee4-1aafdda05019
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5a39aec0-dd22-403a-adaa-95157ed5d665
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 55d9c451-98eb-4346-b08c-f5c595ba79e5
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: b0119d45-bf84-4314-abc3-a4e569d7b099
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b72a0aa0-a735-453e-ba24-81c3bbf38be2
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 876dcb69-06c1-4cba-afe6-6e7a754b6560
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 2
handle: textMedia
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Text & media'
sortOrder: 9
topLevel: false
