childBlocks: ''
field: fb4bae98-1902-4611-9b1c-635f478d5575
fieldLayouts:
  -
    tabs:
      -
        elements:
          -
            fieldUid: aea0f145-e645-4cc0-a527-40ec2aa6a934
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: e7b2fe6b-98c7-4eb1-a270-83d982092073
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b72a0aa0-a735-453e-ba24-81c3bbf38be2
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Settings
        sortOrder: 2
handle: tiles
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Tiles
sortOrder: 19
topLevel: false
