contentColumnType: boolean
fieldGroup: 905b04a9-6392-4043-9b56-6a0a92518b39
handle: bottomFooterNavigation
instructions: ''
name: 'Bottom footer navigation'
searchable: true
settings:
  default: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
