contentColumnType: string
fieldGroup: 27c20eea-7252-47e8-a74b-cc91af2f962e
handle: buttons
instructions: ''
name: Buttons
searchable: true
settings:
  contentTable: '{{%matrixcontent_buttons}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
