contentColumnType: string
fieldGroup: 27c20eea-7252-47e8-a74b-cc91af2f962e
handle: cardMedia
instructions: ''
name: 'Card media'
searchable: true
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - Image
        -
          - value
          - image
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Icon
        -
          - value
          - icon
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - None
        -
          - value
          - none
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
