contentColumnType: text
fieldGroup: 27c20eea-7252-47e8-a74b-cc91af2f962e
handle: codeEmbed
instructions: ''
name: 'Code embed'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
