contentColumnType: string
fieldGroup: 27c20eea-7252-47e8-a74b-cc91af2f962e
handle: columnsPerRow
instructions: ''
name: 'Columns per row'
searchable: true
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - '2'
        -
          - value
          - '2'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '3'
        -
          - value
          - '3'
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - '4'
        -
          - value
          - '4'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '5'
        -
          - value
          - '5'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '6'
        -
          - value
          - '6'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
