contentColumnType: datetime
fieldGroup: 582b4a03-b997-427c-8217-9432af1bd0af
handle: dateOfAction
instructions: ''
name: 'Date of action'
searchable: true
settings:
  minuteIncrement: '30'
  showDate: true
  showTime: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
