contentColumnType: string
fieldGroup: c0b4eec9-4c5d-4eab-a8d0-c04917ed2d40
handle: displayType
instructions: ''
name: 'Display type'
searchable: true
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - Cards
        -
          - value
          - cards
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Table
        -
          - value
          - table
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
