contentColumnType: boolean
fieldGroup: 905b04a9-6392-4043-9b56-6a0a92518b39
handle: footerColumnFourNavigation
instructions: 'Select this option to display this page in the fourth column in the footer navigation'
name: 'Footer column four navigation'
searchable: true
settings:
  default: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
