contentColumnType: text
fieldGroup: 905b04a9-6392-4043-9b56-6a0a92518b39
handle: footerNavigationClasses
instructions: ''
name: 'Footer navigation classes'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
