contentColumnType: boolean
fieldGroup: 905b04a9-6392-4043-9b56-6a0a92518b39
handle: footerColumnTwoNavigation
instructions: 'Select this option to display this page in the second column in the footer navigation'
name: 'Footer column two navigation'
searchable: true
settings:
  default: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
