contentColumnType: text
fieldGroup: 862f0012-849b-4288-82b0-c9606e3e052a
handle: footerText
instructions: ''
name: 'Footer text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
