contentColumnType: string
fieldGroup: 1363d3d4-fc9b-40c8-a7c7-2cf1cdf71cb8
handle: headerFontSize
instructions: ''
name: 'Header font size'
searchable: true
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - Large
        -
          - value
          - large
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Small
        -
          - value
          - small
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
