contentColumnType: text
fieldGroup: 27c20eea-7252-47e8-a74b-cc91af2f962e
handle: navigation
instructions: ''
name: Navigation
searchable: true
translationKeyFormat: null
translationMethod: none
type: verbb\navigation\fields\NavigationField
