contentColumnType: string
fieldGroup: 27c20eea-7252-47e8-a74b-cc91af2f962e
handle: order
instructions: ''
name: Order
searchable: true
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - 'Media left'
        -
          - value
          - mediaLeft
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Media right'
        -
          - value
          - mediaRight
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
