contentColumnType: boolean
fieldGroup: 905b04a9-6392-4043-9b56-6a0a92518b39
handle: primaryNavigation
instructions: 'Tick this if you want this page to display in the primary navigation'
name: 'Primary navigation'
searchable: true
settings:
  default: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
