contentColumnType: string
fieldGroup: 75f9d910-f695-4591-9506-e6cfe921fcd7
handle: protectiveOrderTagSelect
instructions: ''
name: 'Protective order tag select'
searchable: false
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - Registered
        -
          - value
          - registered
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Unregistered
        -
          - value
          - unregistered
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
