contentColumnType: text
fieldGroup: 027716c8-e2e8-4283-8aa2-4913b9ab2af2
handle: seoDescription
instructions: ''
name: 'SEO Description'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
