fieldLayouts:
  e2eabc0a-9a0d-4e67-9d21-ee6fddababbc:
    tabs:
      -
        elements:
          -
            fieldUid: ae4e8073-c51c-40eb-954a-f69461ea781e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bb741c5a-01c9-48d1-9767-bc10900e9d26
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: bottomFooter
name: 'Bottom Footer'
