enableVersioning: true
handle: latestUpdatesIndex
name: 'All latest updates'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  693a5f5f-5f4e-40ad-b3b4-228d13f6dfc9:
    enabledByDefault: true
    hasUrls: true
    template: media/index
    uriFormat: latest-updates
type: single
