enableVersioning: true
handle: pages
name: Pages
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  693a5f5f-5f4e-40ad-b3b4-228d13f6dfc9:
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry.twig
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: edd30d5b-e08a-441a-a528-aea2abfc0e37
type: structure
